spring.application.name=CoffeeTester
spring.servlet.multipart.enabled=true
<<<<<<< HEAD
=======
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
>>>>>>> 2b201f0ce0eb0f90a72031f449d24ff717af3429
spring.web.resources.static-locations=classpath:/static/,file:data/coffee_pictures/
server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=true
