spring.application.name=CoffeeTester
server.port=8081
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
server.servlet.session.timeout=10s
spring.web.resources.static-locations=classpath:/static/,file:data/coffee_pictures/
server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=true
